import type { Metadata } from "next";

import "@/assets/styles/globals.css";
import { poppins } from "@/assets/fonts";
import { Header, PreHeader } from "@/components/layout";
import StoreProvider from "@/store/StoreProvider";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Ecommerce"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html className={`${poppins.className} min-h-[450px] min-w-[375px]`} lang="en">
    <body>
      <StoreProvider>
        <PreHeader />
        <Header />
        {children}
      </StoreProvider>
    </body>
  </html>
);

export default RootLayout;
