import type { Metadata } from "next";

import "@/assets/styles/globals.css";
import { poppins } from "@/assets/fonts";
import { Footer, Header, Info, PreHeader } from "@/components/layout";

import { Provider } from "./provider";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Ecommerce"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html className={`${poppins.className}  h-screen min-h-[450px] min-w-[375px] `} lang="en">
    <body className="flex h-full flex-col">
      <Provider>
        <PreHeader />
        <Header />
        {children}
        <Info bg="gray" />
        <Footer />
      </Provider>
    </body>
  </html>
);

export default RootLayout;
